[package]
name = "ori_fold"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
serde_repr = "0.1.20"
exact_number = { path = "./exact_number" }
