[package]
name = "robust_geometry"
version = "0.1.0"
edition = "2024"

[dependencies]
generic-array = "1.3.5"
nalgebra = "0.34.1"
paste = "1.0.15"
typenum = "1.19.0"

[dev-dependencies]
rand = "0.9.2"
rand_distr = "0.5.1"
rand_pcg = "0.9.0"
rug = "1.28.0"
